# Generated by Django 4.0.6 on 2022-07-30 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('especialidades', '0001_initial'),
        ('medicos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medico',
            options={'ordering': ['nome'], 'verbose_name': 'Médico', 'verbose_name_plural': 'Médicos'},
        ),
        migrations.AddField(
            model_name='medico',
            name='especialidades',
            field=models.ManyToManyField(null=True, to='especialidades.especialidade'),
        ),
    ]
