# Generated by Django 4.0.6 on 2022-07-30 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('especialidades', '0001_initial'),
        ('medicos', '0002_alter_medico_options_medico_especialidades'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medico',
            name='especialidades',
            field=models.ManyToManyField(to='especialidades.especialidade'),
        ),
    ]
