# Generated by Django 4.0.6 on 2022-07-30 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendas', '0002_remove_agenda_horarios_agenda_horarios'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agenda',
            old_name='horarios',
            new_name='horario',
        ),
        migrations.AlterField(
            model_name='horario',
            name='horario',
            field=models.TimeField(unique=True),
        ),
    ]
